env:
  global:
    - DOCKER_VERSION=1.10.1-0~trusty
sudo: required
services:
  - docker
before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
script:
  - ./build.sh
