env:
  global:
    - DOCKER_VERSION=1.10.1-0~trusty
sudo: required
services:
  - docker
before_install:
  - sudo apt-get -o Dpkg::Options::="--force-confnew" install -y docker-engine=${DOCKER_VERSION}
script:
  - docker version
  - docker login --email="$DOCKER_EMAIL" --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - ./build.sh
